version: '3.8'

services:
  web:
    build:
      context: ./web
      target: dev
    ports:
      - '9001:3000'
    volumes:
      - './web:/app'
      - '/app/node_modules'
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
