version: '3.8'

services:
  web:
    build:
      context: ./web
      target: dev
    ports:
      - '9000:3000'
    volumes:
      - './web:/app'
      - '/app/node_modules'
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

    