name: Build and Deploy to Staging

on:
  pull_request:
    branches: ['dev']
    types:
      - closed
  workflow_dispatch:

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Staging image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: omci/notionsync:staging

      - name: Invoke deployment hook
        if: success()
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL_DEV }}