name: Compile and push client and server image for staging 

on:
for the dev branch
  pull_request:
    branches: ["dev"]
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true 

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        env:
          SECRET_KEY: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          PAYLOAD='{}'
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET_KEY" | awk '{print $2}')
          SIGNATURE="sha256=$SIGNATURE"

          curl -X POST -H "Content-Type: application/json" -H "X-Hub-Signature: $SIGNATURE" -d "$PAYLOAD" ${{ secrets.WEBHOOK_URL_DEV }}